version: '3.4'

networks:
  goinvest:

services:
  postgres:
    image: postgres:10.0
    ports: 
    - "5432:5432"
    volumes: 
    - $PWD/pg_data:/var/lib/postgresql/data
    environment:
    - POSTGRES_PASSWORD
    - POSTGRES_USER
    - POSTGRES_DB
    networks:
      goinvest:
        aliases:
        - pg
        
  memcached:
    image: memcached:1.5.2
    ports:
    - "11211:11211"
    networks:
      goinvest:
        aliases:
        - cache
    deploy:
      resources:
        limits:
          memory: '200m'
        reservations:
          memory: '100m'

  pgadmin4:
    image: thajeztah/pgadmin4
    ports:
    - "5050:5050"
    networks:
      goinvest:
        aliases:
        - pgadmin
    deploy:
      resources:
        limits:
          memory: '300m'
        reservations:
          memory: '150m'

