CREATE TABLE instruments (
        ID bigint GENERATED BY DEFAULT AS IDENTITY,
        SHORT_NAME text,
        SEC_ID text PRIMARY KEY,
        RAW text,
        UPDATED_AT timestamp,
        DELETED_AT timestamp,
        CREATED_AT timestamp
)
